### ISSUE TITLE
Problems when trying to replace the mscoco model with the model trained with my own dataset

### ISSUE THREAD

**Issue by satoshiSchubert** [shangtse/robust-physical-attack#10]
Thank you so much for your excellent work! However, I recently encountered a problem when trying to generate my own adversarial patch:
I want to try to use the faster-rcnn-inception model trained on my own dataset to generate specific adversarial patches, but I found that even under the same config file (I am sure it is the same), the generated faster-rcnn-inception model(by tensorflow object detection API) is still somewhat different from the mscoco model in the tensorflow model zoo(which used in the jupyter notebook)  ,and i found the differences are usually in the naming and structure of the parameters, which leads to an error in the method : `'.graph.get_tensor_by_name'` in the jupyter notebook. I spent several days and still don't know how to train a model with the same structure as the model in model zoo.
Therefore, I use Netron to match related variables in the two models, hoping to replace the original variable names with some of the same features (such as similar naming, the same shape, size, etc.). 
E.g:
in `class ModelContainer()`, i replaced this code: 
```
with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
                serialized_graph = fid.read()
                detection_graph_def.ParseFromString(serialized_graph)
                tf.import_graph_def(detection_graph_def, name='detection',
                                    input_map={
                                               'Preprocessor/map/TensorArrayStack/TensorArrayGatherV3:0':self.patched_input_,
                                               '**Reshape_7:0**':self.rpn_nms_bboxes_placeholder_,
                                               '**Reshape_8:0**':self.rpn_nms_indices_placeholder_,
                                              })

            # Recreate tensors we just replaced in the input_map
            self.rpn_nms_bboxes_ = tf.reshape(self.graph.get_tensor_by_name('**detection/Reshape_6:0**'), self.graph.get_tensor_by_name('**detection/stack_3:0**'), name='detection/Reshape_7')
            self.rpn_nms_indices_ = tf.reshape(self.graph.get_tensor_by_name('**detection/mul_1:0**'), self.graph.get_tensor_by_name('**detection/Reshape_8/shape:0**'), name='detection/Reshape_8') 
```
with:
```
with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
                serialized_graph = fid.read()
                detection_graph_def.ParseFromString(serialized_graph)
                tf.import_graph_def(detection_graph_def, name='detection',
                                    input_map={
                                               'Preprocessor/map/TensorArrayStack/TensorArrayGatherV3:0':self.patched_input_,
                                               'Reshape:0':self.rpn_nms_bboxes_placeholder_,
                                               'Reshape_1:0':self.rpn_nms_indices_placeholder_,
                                              })

            # Recreate tensors we just replaced in the input_map
            self.rpn_nms_bboxes_ = tf.reshape(self.graph.get_tensor_by_name('detection/Reshape_3:0'), self.graph.get_tensor_by_name('detection/stack_3:0'), name='detection/Reshape')
            self.rpn_nms_indices_ = tf.reshape(self.graph.get_tensor_by_name('detection/ExpandDims_1:0'), self.graph.get_tensor_by_name('detection/Reshape_1/shape:0'), name='detection/Reshape_1')  
```
It can be seen that the part with'** **' has been replaced.

However, since I don't know the principle by which these variables are selected, many problems have been encountered after this modify.

So hope to know: Based on what principles did you select these variables with '** **'? What principles can be used to find these ‘important’ variables?

In addition, I attached a picture, which is a screenshot of the work when using Netron to match parameter names.

![D8L~JUL`8UV11DSC6`4R@LL](https://user-images.githubusercontent.com/44137161/106389642-5ce1d580-641f-11eb-8ee1-03f5da61b0dc.png)

**Comment by dxoigmn** [comment]
`Reshape_7` and `Reshape_8` are the tensors in the graph that are the non-max suppressed outputs from the region proposal network. As you noticed, the name of these tensors will change depending upon the version of TF's Object Detection API you use and the particular choice of model. I suggest you install the version in the `Pipfile` (fe748d4a4a1576b57c279014ac0ceb47344399c4). If I had to hazard a guess in the code which Tensors these correspond to, I would guess one of these: 

https://github.com/tensorflow/models/blob/fe748d4a4a1576b57c279014ac0ceb47344399c4/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py#L1625

Knowing that, you can just print out the tensor names to see which one is which and then you'll understand how the code maps to the tensors. That should help you discover which tensor names to use for your model.

**Comment by satoshiSchubert** [comment]
Thank you for your detailed reply!  I finally solved this problem by matching the inference graph, and here I attached my code for it might help others facing the same issue. 
```
with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
                serialized_graph = fid.read()
                detection_graph_def.ParseFromString(serialized_graph)
                tf.import_graph_def(detection_graph_def, name='detection',
                                    input_map={
                                               'Preprocessor/map/TensorArrayStack/TensorArrayGatherV3:0':self.patched_input_,
                                               'CropAndResize/Reshape:0':self.rpn_nms_bboxes_placeholder_,
                                               'CropAndResize/Reshape_1:0':self.rpn_nms_indices_placeholder_,
                                              })

            # Recreate tensors we just replaced in the input_map
            self.rpn_nms_bboxes_ = tf.reshape(self.graph.get_tensor_by_name('detection/map/TensorArrayStack/TensorArrayGatherV3:0'), self.graph.get_tensor_by_name('detection/CropAndResize/Reshape/shape:0'), name='detection/Reshape')
            self.rpn_nms_indices_ = tf.reshape(self.graph.get_tensor_by_name('detection/CropAndResize/mul:0'), self.graph.get_tensor_by_name('detection/CropAndResize/Reshape_1/shape:0'), name='detection/Reshape_1') 
            
```
