### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by HoneyehYz** [shangtse/robust-physical-attack#11]
Hi, 
I tried running your project in google colab, I got some errors that were solvable but this one I have no idea how to fix it. It seems that there is an issue with numpy version> I tried to install another version but then it complains about Tensorflow-addons as it was needed for optimization part. 
AttributeError: 'module' object has no attribute 'stack' 
I would appreciate it if you can help me to fix that.

**Comment by dxoigmn** [comment]
Looks like the default tensorflow version on Colab has changed. You'll want to replace the "Install Dependencies" cell with the following, which matches the dependencies listed in the Pipfile.
```
!pip install tensorflow-gpu==1.13.2
!apt-get install -y -qq protobuf-compiler python-pil python-lxml
!git clone --quiet https://github.com/tensorflow/models.git
!cd models; git checkout fe748d4a4a1576b57c279014ac0ceb47344399c4
 
import os
os.chdir('models/research')
!protoc object_detection/protos/*.proto --python_out=.

import sys
sys.path.append('/content/models/research/slim')
```

Note that installing tensorflow may require you to restart the runtime.

**Comment by HoneyehYz** [comment]
Thanks for the response. so I dont need to install `!pip install tensorflow-addons` any more? Before this error I was getting another Attribute error saying `module object do not have any attribute contrib` and after some searches I realized that we need `tensorflow-addons`.

**Comment by HoneyehYz** [comment]
Thank you so much for helping me and also for your great and neat code. This will be an awesome learning reference for me.
