### ISSUE TITLE
python2 from cStringIO import StringIO

### ISSUE THREAD

**Issue by gmt710** [shangtse/robust-physical-attack#3]
jupyter notebook:
python2 :from cStringIO import StringIO
python3 :from io import BytesIO

Replace StringIO with BytesIO.

**Comment by shangtse** [comment]
Could you explain your question/comment a bit more?
I guess you are suggesting something related to Python 2 -> 3 transition?
Here the code was written purely in Python 2 because at the time of development Tensorflow Object Detection API only supported Python 2.

**Comment by gmt710** [comment]
@shangtse Yes,I compile my code using Python3, and so does the Tensorflow Object Detection API.
