### ISSUE TITLE
How did you create the mask?

### ISSUE THREAD

**Issue by sadafgulshad1** [shangtse/robust-physical-attack#5]
Two masks which you are using for stop sign how did you create them? Furthermore, here you are considering only the stop sign so only stop sign masks are used but what if I want to use this method for other datasets  then I will have to create the masks for specific objects in images?

**Comment by shangtse** [comment]
You can just use any stop sign image (e.g. https://en.wikipedia.org/wiki/File:Stop_sign(standard).svg) and use pixel value thresholding to create a mask. We use the mask to constrain the shape and add a regularization term in the loss function to constrain the color. For other datasets you can use the same method, but some object classes may need more complex constraints than only shape and color.

**Comment by sadafgulshad1** [comment]
Thank you.
