### ISSUE TITLE
version of tesnsorflow and cuda?

### ISSUE THREAD

**Issue by i-chaochen** [shangtse/robust-physical-attack#7]
Hi, thanks for sharing this code

I think I have the cuda version problem when trying your code.

After I  installed dependencies and patches without problems
```
make deps
```

and I tried ``` make 2d_untargeted_attack ``` I got 

```ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory```

If I understood correctly, this is because my cuda is 10.2 and my tensorflow-gpu is 1.14.0, and yours cuda is 10.0 and tensorflow is? So If I want to run it successfully, I need to set your cuda as 10.2? 

I checked ```Makefile``` and ```~/.local/share/virtualenvs/robust-physical-attack-L90Q9SNz/lib``` , I couldn't find where to set up the version of cuda or tensorflow. 

I am not familar with Pipenv, I wonder do you know how to set up the related version of cuda and tensorflow? or is any other I'm missed?

Thanks in advance!

**Comment by dxoigmn** [comment]
We only tested the new code against Tensorflow 1.13.x, which links to CUDA 10.0 by default. You can find directions for installing CUDA 10.0 using apt here: https://www.tensorflow.org/install/gpu#install_cuda_with_apt.

Alternatively, you can try finding a build of Tensorflow 1.13.x that links to CUDA 10.2, and then install that within the virtual environment created by Pipenv. You can find more information about how to use Pipenv here: https://pipenv.kennethreitz.org/.

**Comment by i-chaochen** [comment]
> We only tested the new code against Tensorflow 1.13.x, which links to CUDA 10.0 by default. You can find directions for installing CUDA 10.0 using apt here: https://www.tensorflow.org/install/gpu#install_cuda_with_apt.
> 
> Alternatively, you can try finding a build of Tensorflow 1.13.x that links to CUDA 10.2, and then install that within the virtual environment created by Pipenv. You can find more information about how to use Pipenv here: https://pipenv.kennethreitz.org/.

Thanks for the explanation. 

I made some changes on Makefile to run your model without pipenv on tensorflow 1.14x and cuda 10.2, it works!

**Comment by i-chaochen** [comment]
As a side note, I wonder how long the training you guys costed?

@dxoigmn  I only have 1 Nvidia 2080 Ti,  and it's already training one night.
