### ISSUE TITLE
what's the relationship between robust_physical_attack.ipynb and shapeshifter2d.py

### ISSUE THREAD

**Issue by gptcod** [shangtse/robust-physical-attack#8]
what's the relationship between robust_physical_attack.ipynb and shapeshifter2d.py?Thanks a lot.

**Comment by dxoigmn** [comment]
We rewrote the notebook (robust_physical_attack.ipynb) into a python script (shapeshifter2d.py). The Python script is newer and uses the Object Detection APIs to construct the graph rather than doing graph surgery like the notebook does.
