### ISSUE TITLE
how to get perturbations in shapeshifter2d.py?

### ISSUE THREAD

**Issue by gptcod** [shangtse/robust-physical-attack#9]
I read and run the code, but don't get perturbations image.I guess line 133 code: input_images_ = create_composited_images(args.batch_size, textures_, textures_masks).But I am not sure.I truly appreciate your  help.

**Comment by dxoigmn** [comment]
If you save the output via --logdir, you can then point Tensorboard to that directory and see the perturbation evolve over the attack iterations. You can then save the perturbation by right clicking on the image and saving via your web browser. All this logic happens in https://github.com/shangtse/robust-physical-attack/blob/master/shapeshifter.py#L614
